name: target_extension
description: Extensions for functional domain modeling in Dart.
version: 0.7.1
repository: https://github.com/callius/target-dart/tree/main/packages/target_extension
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dartz: ^0.10.1
  target:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target
      ref: v0.7.1

dev_dependencies:
  lint: ^2.2.0
  test: null
