name: target_extension
description: Extensions for functional domain modeling in Dart.
version: 0.4.0
repository: https://github.com/callius/target-dart/tree/main/packages/target_extension
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  collection: ^1.17.1
  dartz: ^0.10.1

dev_dependencies:
  lint: ^2.1.2
  test: null
