name: target_extension
description: Extensions for functional domain modeling in Dart.
version: 0.1.2
repository: https://github.com/callius/target-dart/tree/main/packages/target_extension
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  collection: ^1.17.0
  dartz: ^0.10.1

dev_dependencies:
  lints: ^2.0.1
  test: null
