builders:
  core_annotation:
    import: "package:target_annotation_processor/target_annotation_processor.dart"
    builder_factories: [ "modelBuilder" ]
    build_extensions: { ".dart": [ ".core.dart" ] }
    auto_apply: dependents
    build_to: source
