name: target_annotation_processor
description: Functional domain modeling in Dart.
version: 0.2.0
repository: https://github.com/callius/target-dart/tree/main/packages/target_annotation_processor
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.0
  code_builder: ^4.5.0
  collection: ^1.17.2
  equatable: ^2.0.5
  target:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target
      ref: v0.2.1
  target_annotation:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target_annotation
      ref: v0.2.1
  target_extension:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target_extension
      ref: v0.2.1
  dart_style: ^2.3.1
  dartz: ^0.10.1
  source_gen: ^1.3.2

dev_dependencies:
  build_runner: null
  build_test: ^2.1.7
  lints: ^2.1.1
  source_gen_test: ^1.0.5
  test: null
