name: target_annotation_processor
description: Functional domain modeling in Dart.
version: 0.11.0
repository: https://github.com/callius/target-dart/tree/main/packages/target_annotation_processor
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  analyzer: '>=7.0.0 <8.0.0'
  build: ^3.0.0
  code_builder: ^4.10.1
  collection: ^1.19.0
  dart_style: ^3.0.1
  equatable: ^2.0.7
  source_gen: ^3.0.0
  target:
    path: ../target
  #    git:
  #      url: https://github.com/callius/target-dart
  #      path: packages/target
  #      ref: v0.11.0
  target_annotation:
    path: ../target_annotation
  #    git:
  #      url: https://github.com/callius/target-dart
  #      path: packages/target_annotation
  #      ref: v0.11.0
  target_extension:
    path: ../target_extension
  #    git:
  #      url: https://github.com/callius/target-dart
  #      path: packages/target_extension
  #      ref: v0.11.0

dev_dependencies:
  build_runner: null
  build_test: ^3.3.1
  lint: ^2.8.0
  source_gen_test: ^1.3.1
  test: null
