name: target_annotation_processor
description: Functional domain modeling in Dart.
version: 0.1.1
repository: https://github.com/callius/target-dart/tree/main/packages/target_annotation_processor
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  analyzer: ^5.10.0
  build: ^2.3.1
  code_builder: ^4.4.0
  collection: ^1.17.0
  target:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target
  target_annotation:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target_annotation
  target_extension:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target_extension
  dart_style: ^2.3.0
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: null
  build_test: ^2.1.7
  freezed: ^2.3.2
  lints: ^2.0.1
  source_gen_test: ^1.0.4
  test: null
