name: target_annotation_processor
description: Functional domain modeling in Dart.
version: 0.9.0
repository: https://github.com/callius/target-dart/tree/main/packages/target_annotation_processor
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  analyzer: '>=7.0.0 <8.0.0'
  build: ^2.4.2
  code_builder: ^4.10.1
  collection: ^1.19.0
  dart_style: ^3.0.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  source_gen: ^2.0.0
  target:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target
      ref: v0.9.0
  target_annotation:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target_annotation
      ref: v0.9.0
  target_extension:
    git:
      url: https://github.com/callius/target-dart
      path: packages/target_extension
      ref: v0.9.0

dev_dependencies:
  build_runner: null
  build_test: ^2.2.3
  lint: ^2.6.1
  source_gen_test: ^1.1.1
  test: null
