targets:
  $default:
    builders:
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
