name: target
description: Functional domain modeling in Dart.
version: 0.7.0
repository: https://github.com/callius/target-dart/tree/main/packages/target
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  lint: ^2.2.0
  test: null
