name: target
description: Functional domain modeling in Dart.
version: 0.1.0
repository: https://github.com/callius/target-dart/tree/main/packages/target
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  collection: ^1.17.0
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  build_runner: null
  lints: ^2.0.1
  mockito: ^5.4.0
  test: null
