name: target
description: Functional domain modeling in Dart.
version: 0.12.0
repository: https://github.com/callius/target-dart/tree/main/packages/target
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  equatable: ^2.0.7

dev_dependencies:
  lint: ^2.8.0
  test: null
