name: target
description: Functional domain modeling in Dart.
version: 0.2.2
repository: https://github.com/callius/target-dart/tree/main/packages/target
issue_tracker: https://github.com/callius/target-dart/issues
homepage: https://github.com/callius/target-dart

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  collection: ^1.17.1
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  lint: ^2.1.2
  test: null
